export const taxRuless = [
  // === General Tax Rules (30) ===
  { id: '1', title: 'Rule 1: Tax Obligation', info: 'Everyone earning income must pay tax.' },
  { id: '2', title: 'Rule 2: Filing Deadline', info: 'Taxes should be filed before due date yearly.' },
  { id: '3', title: 'Rule 3: Record Keeping', info: 'Keep receipts and records for proof of payment.' },
  { id: '4', title: 'Rule 4: Double Taxation', info: 'Avoid paying tax twice on the same income.' },
  { id: '5', title: 'Rule 5: Deductions', info: 'Some expenses reduce your taxable income.' },
  { id: '6', title: 'Rule 6: Exemptions', info: 'Certain incomes like scholarships may be tax-free.' },
  { id: '7', title: 'Rule 7: Refunds', info: 'If you overpay, you can request a tax refund.' },
  { id: '8', title: 'Rule 8: Penalties', info: 'Late tax filing attracts fines or penalties.' },
  { id: '9', title: 'Rule 9: Tax Audits', info: 'Tax authorities can verify your declarations.' },
  { id: '10', title: 'Rule 10: Employment Tax', info: 'Employers deduct tax before paying salary.' },
  { id: '11', title: 'Rule 11: Self-Employed', info: 'Freelancers must calculate and pay own tax.' },
  { id: '12', title: 'Rule 12: Withholding Tax', info: 'A portion of payment is kept as tax at source.' },
  { id: '13', title: 'Rule 13: Capital Gains', info: 'Profit from selling assets can be taxed.' },
  { id: '14', title: 'Rule 14: Depreciation', info: 'Assets lose value and affect tax value.' },
  { id: '15', title: 'Rule 15: Allowances', info: 'Allowances like transport can reduce taxable pay.' },
  { id: '16', title: 'Rule 16: International Income', info: 'Foreign earnings may still attract local tax.' },
  { id: '17', title: 'Rule 17: Corporate Tax', info: 'Companies pay tax on their profits.' },
  { id: '18', title: 'Rule 18: Personal Income Tax', info: 'Individuals pay based on income brackets.' },
  { id: '19', title: 'Rule 19: Estimated Tax', info: 'Pay in advance if regular deductions don’t apply.' },
  { id: '20', title: 'Rule 20: Tax Identification Number', info: 'Every taxpayer should have a TIN.' },
  { id: '21', title: 'Rule 21: VAT Collection', info: 'Businesses collect VAT on goods/services sold.' },
  { id: '22', title: 'Rule 22: E-filing', info: 'You can file and pay tax online.' },
  { id: '23', title: 'Rule 23: Donations', info: 'Registered charity donations can reduce tax.' },
  { id: '24', title: 'Rule 24: Tax Clearance', info: 'Needed to verify you’ve paid taxes fully.' },
  { id: '25', title: 'Rule 25: Pension Deductions', info: 'Pension contributions can lower taxable income.' },
  { id: '26', title: 'Rule 26: Estate Tax', info: 'Assets passed after death can be taxed.' },
  { id: '27', title: 'Rule 27: Stamp Duty', info: 'Documents and transactions may attract duty fees.' },
  { id: '28', title: 'Rule 28: Excise Duties', info: 'Applied to goods like alcohol and tobacco.' },
  { id: '29', title: 'Rule 29: Customs Duty', info: 'Imported goods are taxed by customs.' },
  { id: '30', title: 'Rule 30: Environmental Tax', info: 'Businesses may pay for environmental impact.' },

  // === Nigerian Tax Laws (15) ===
  { id: '31', title: 'Nigerian Rule 1', info: 'Personal Income Tax Act (PITA) governs income tax.' },
  { id: '32', title: 'Nigerian Rule 2', info: 'Companies Income Tax Act (CITA) regulates company tax.' },
  { id: '33', title: 'Nigerian Rule 3', info: 'Value Added Tax Act controls VAT collection.' },
  { id: '34', title: 'Nigerian Rule 4', info: 'Capital Gains Tax Act covers property gains.' },
  { id: '35', title: 'Nigerian Rule 5', info: 'Petroleum Profits Tax applies to oil firms.' },
  { id: '36', title: 'Nigerian Rule 6', info: 'Education Tax funds tertiary institutions.' },
  { id: '37', title: 'Nigerian Rule 7', info: 'Stamp Duties apply on legal documents.' },
  { id: '38', title: 'Nigerian Rule 8', info: 'Withholding Tax for payments made to vendors.' },
  { id: '39', title: 'Nigerian Rule 9', info: 'Tertiary Education Trust Fund (TETFund) Act.' },
  { id: '40', title: 'Nigerian Rule 10', info: 'Customs and Excise Management Act for imports.' },
  { id: '41', title: 'Nigerian Rule 11', info: 'FIRS Act manages federal tax collection.' },
  { id: '42', title: 'Nigerian Rule 12', info: 'Joint Tax Board harmonizes state/federal taxes.' },
  { id: '43', title: 'Nigerian Rule 13', info: 'National Housing Fund contributions taxed.' },
  { id: '44', title: 'Nigerian Rule 14', info: 'Tax Appeal Tribunal Act for disputes.' },
  { id: '45', title: 'Nigerian Rule 15', info: 'Finance Act updates tax rates and rules yearly.' },

  // === Key Taxes (3) ===
  { id: '46', title: 'PAYE', info: 'Pay-As-You-Earn: employer deducts tax from salaries.' },
  { id: '47', title: 'VAT', info: 'Value Added Tax: 7.5% on goods and services in Nigeria.' },
  { id: '48', title: 'Company Tax', info: 'Companies pay 30% (large firms) or 20% (SMEs) on profits.' },
];